export const SET_ALL_CODES = "SET_ALL_CODES";
export const SET_ALL_LOCATIONS = "SET_ALL_LOCATIONS";
export const SET_ALL_REVIEWS = "SET_ALL_REVIEWS";
export const ADD_CODE = "ADD_CODE";
export const MARK_VISITED_LOCATION = "MARK_VISITED_LOCATION";
export const SIGN_OUT = "SIGN_OUT";
export const SET_USER_REVIEWS = "SET_USER_REVIEWS";
export const SET_PRIZE_TIMER = "SET_PRIZE_TIMER";
export const UPDATE_PRIZE_TIMER = "UPDATE_PRIZE_TIMER";
//DELETE
export const MARK_UNVISITED_LOCATION = "MARK_UNVISITED_LOCATION";
export const TIMER_IS_DONE = "TIMER_IS_DONE";
export const SET_WINNERS = "SET_WINNERS";
